# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "Llama2 125M training"

[profiling]
enable_profiling = false # true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = false # true
save_tb_folder = "tb"

[model]
name = "llama2"
flavor = "125M"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./test/assets/test_tiktoken.model"

[optimizer]
name = "AdamW"
lr = 3e-3

[training]
batch_size = 8
seq_len = 2048
warmup_steps = 480  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 4800
data_parallel_degree = -1
tensor_parallel_degree = 1  # dp-only would be sufficient for 7B
mixed_precision_param = "float32"  # @xinhao: avoid fsdp inner loop b16 and fp32 compute together
compile = false
#dataset = "c4"
dataset = "c4_test"  # supported datasets: c4_test (2K), c4 (177M)

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
#mode = 'selective'  # ['none', 'selective', 'full']
mode = 'none'
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
